runtime: nodejs20

handlers:
  # Serve all static files with url ending with a file extension

  - url: /(.*\.css)
    mime_type: text/css
    static_files: dist/\1
    secure: always
    upload: dist/(.*\.css)

  - url: /(.*\.html)
    mime_type: text/html
    static_files: dist/\1
    upload: dist/(.*\.html)
    secure: always

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: dist/\1
    upload: dist/(.*\.js)
    secure: always

  - url: /(.*\.txt)
    mime_type: text/plain
    static_files: dist/\1
    upload: dist/(.*\.txt)
    secure: always

  - url: /(.*\.xml)
    mime_type: application/xml
    static_files: dist/\1
    upload: dist/(.*\.xml)
    secure: always

  # image files
  - url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
    static_files: dist/\1
    upload: dist/(.*\.(bmp|gif|ico|jpeg|jpg|png))
    secure: always

  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always